-- ModuleScript

local Module = {}

function Module.IsEven(PassedNumber)
	if type(PassedNumber) ~= "number" then
		error("Passed number not a number.")
		return nil
	end

	if PassedNumber < -200 or PassedNumber > 200 then
		print("Number not supported")
	end

	if PassedNumber == -200 then
		return true
	end
	if PassedNumber == -199 then
		return false
	end
	if PassedNumber == -198 then
		return true
	end
	if PassedNumber == -197 then
		return false
	end
	if PassedNumber == -196 then
		return true
	end
	if PassedNumber == -195 then
		return false
	end
	if PassedNumber == -194 then
		return true
	end
	if PassedNumber == -193 then
		return false
	end
	if PassedNumber == -192 then
		return true
	end
	if PassedNumber == -191 then
		return false
	end
	if PassedNumber == -190 then
		return true
	end
	if PassedNumber == -189 then
		return false
	end
	if PassedNumber == -188 then
		return true
	end
	if PassedNumber == -187 then
		return false
	end
	if PassedNumber == -186 then
		return true
	end
	if PassedNumber == -185 then
		return false
	end
	if PassedNumber == -184 then
		return true
	end
	if PassedNumber == -183 then
		return false
	end
	if PassedNumber == -182 then
		return true
	end
	if PassedNumber == -181 then
		return false
	end
	if PassedNumber == -180 then
		return true
	end
	if PassedNumber == -179 then
		return false
	end
	if PassedNumber == -178 then
		return true
	end
	if PassedNumber == -177 then
		return false
	end
	if PassedNumber == -176 then
		return true
	end
	if PassedNumber == -175 then
		return false
	end
	if PassedNumber == -174 then
		return true
	end
	if PassedNumber == -173 then
		return false
	end
	if PassedNumber == -172 then
		return true
	end
	if PassedNumber == -171 then
		return false
	end
	if PassedNumber == -170 then
		return true
	end
	if PassedNumber == -169 then
		return false
	end
	if PassedNumber == -168 then
		return true
	end
	if PassedNumber == -167 then
		return false
	end
	if PassedNumber == -166 then
		return true
	end
	if PassedNumber == -165 then
		return false
	end
	if PassedNumber == -164 then
		return true
	end
	if PassedNumber == -163 then
		return false
	end
	if PassedNumber == -162 then
		return true
	end
	if PassedNumber == -161 then
		return false
	end
	if PassedNumber == -160 then
		return true
	end
	if PassedNumber == -159 then
		return false
	end
	if PassedNumber == -158 then
		return true
	end
	if PassedNumber == -157 then
		return false
	end
	if PassedNumber == -156 then
		return true
	end
	if PassedNumber == -155 then
		return false
	end
	if PassedNumber == -154 then
		return true
	end
	if PassedNumber == -153 then
		return false
	end
	if PassedNumber == -152 then
		return true
	end
	if PassedNumber == -151 then
		return false
	end
	if PassedNumber == -150 then
		return true
	end
	if PassedNumber == -149 then
		return false
	end
	if PassedNumber == -148 then
		return true
	end
	if PassedNumber == -147 then
		return false
	end
	if PassedNumber == -146 then
		return true
	end
	if PassedNumber == -145 then
		return false
	end
	if PassedNumber == -144 then
		return true
	end
	if PassedNumber == -143 then
		return false
	end
	if PassedNumber == -142 then
		return true
	end
	if PassedNumber == -141 then
		return false
	end
	if PassedNumber == -140 then
		return true
	end
	if PassedNumber == -139 then
		return false
	end
	if PassedNumber == -138 then
		return true
	end
	if PassedNumber == -137 then
		return false
	end
	if PassedNumber == -136 then
		return true
	end
	if PassedNumber == -135 then
		return false
	end
	if PassedNumber == -134 then
		return true
	end
	if PassedNumber == -133 then
		return false
	end
	if PassedNumber == -132 then
		return true
	end
	if PassedNumber == -131 then
		return false
	end
	if PassedNumber == -130 then
		return true
	end
	if PassedNumber == -129 then
		return false
	end
	if PassedNumber == -128 then
		return true
	end
	if PassedNumber == -127 then
		return false
	end
	if PassedNumber == -126 then
		return true
	end
	if PassedNumber == -125 then
		return false
	end
	if PassedNumber == -124 then
		return true
	end
	if PassedNumber == -123 then
		return false
	end
	if PassedNumber == -122 then
		return true
	end
	if PassedNumber == -121 then
		return false
	end
	if PassedNumber == -120 then
		return true
	end
	if PassedNumber == -119 then
		return false
	end
	if PassedNumber == -118 then
		return true
	end
	if PassedNumber == -117 then
		return false
	end
	if PassedNumber == -116 then
		return true
	end
	if PassedNumber == -115 then
		return false
	end
	if PassedNumber == -114 then
		return true
	end
	if PassedNumber == -113 then
		return false
	end
	if PassedNumber == -112 then
		return true
	end
	if PassedNumber == -111 then
		return false
	end
	if PassedNumber == -110 then
		return true
	end
	if PassedNumber == -109 then
		return false
	end
	if PassedNumber == -108 then
		return true
	end
	if PassedNumber == -107 then
		return false
	end
	if PassedNumber == -106 then
		return true
	end
	if PassedNumber == -105 then
		return false
	end
	if PassedNumber == -104 then
		return true
	end
	if PassedNumber == -103 then
		return false
	end
	if PassedNumber == -102 then
		return true
	end
	if PassedNumber == -101 then
		return false
	end
	if PassedNumber == -100 then
		return true
	end
	if PassedNumber == -99 then
		return false
	end
	if PassedNumber == -98 then
		return true
	end
	if PassedNumber == -97 then
		return false
	end
	if PassedNumber == -96 then
		return true
	end
	if PassedNumber == -95 then
		return false
	end
	if PassedNumber == -94 then
		return true
	end
	if PassedNumber == -93 then
		return false
	end
	if PassedNumber == -92 then
		return true
	end
	if PassedNumber == -91 then
		return false
	end
	if PassedNumber == -90 then
		return true
	end
	if PassedNumber == -89 then
		return false
	end
	if PassedNumber == -88 then
		return true
	end
	if PassedNumber == -87 then
		return false
	end
	if PassedNumber == -86 then
		return true
	end
	if PassedNumber == -85 then
		return false
	end
	if PassedNumber == -84 then
		return true
	end
	if PassedNumber == -83 then
		return false
	end
	if PassedNumber == -82 then
		return true
	end
	if PassedNumber == -81 then
		return false
	end
	if PassedNumber == -80 then
		return true
	end
	if PassedNumber == -79 then
		return false
	end
	if PassedNumber == -78 then
		return true
	end
	if PassedNumber == -77 then
		return false
	end
	if PassedNumber == -76 then
		return true
	end
	if PassedNumber == -75 then
		return false
	end
	if PassedNumber == -74 then
		return true
	end
	if PassedNumber == -73 then
		return false
	end
	if PassedNumber == -72 then
		return true
	end
	if PassedNumber == -71 then
		return false
	end
	if PassedNumber == -70 then
		return true
	end
	if PassedNumber == -69 then
		return false
	end
	if PassedNumber == -68 then
		return true
	end
	if PassedNumber == -67 then
		return false
	end
	if PassedNumber == -66 then
		return true
	end
	if PassedNumber == -65 then
		return false
	end
	if PassedNumber == -64 then
		return true
	end
	if PassedNumber == -63 then
		return false
	end
	if PassedNumber == -62 then
		return true
	end
	if PassedNumber == -61 then
		return false
	end
	if PassedNumber == -60 then
		return true
	end
	if PassedNumber == -59 then
		return false
	end
	if PassedNumber == -58 then
		return true
	end
	if PassedNumber == -57 then
		return false
	end
	if PassedNumber == -56 then
		return true
	end
	if PassedNumber == -55 then
		return false
	end
	if PassedNumber == -54 then
		return true
	end
	if PassedNumber == -53 then
		return false
	end
	if PassedNumber == -52 then
		return true
	end
	if PassedNumber == -51 then
		return false
	end
	if PassedNumber == -50 then
		return true
	end
	if PassedNumber == -49 then
		return false
	end
	if PassedNumber == -48 then
		return true
	end
	if PassedNumber == -47 then
		return false
	end
	if PassedNumber == -46 then
		return true
	end
	if PassedNumber == -45 then
		return false
	end
	if PassedNumber == -44 then
		return true
	end
	if PassedNumber == -43 then
		return false
	end
	if PassedNumber == -42 then
		return true
	end
	if PassedNumber == -41 then
		return false
	end
	if PassedNumber == -40 then
		return true
	end
	if PassedNumber == -39 then
		return false
	end
	if PassedNumber == -38 then
		return true
	end
	if PassedNumber == -37 then
		return false
	end
	if PassedNumber == -36 then
		return true
	end
	if PassedNumber == -35 then
		return false
	end
	if PassedNumber == -34 then
		return true
	end
	if PassedNumber == -33 then
		return false
	end
	if PassedNumber == -32 then
		return true
	end
	if PassedNumber == -31 then
		return false
	end
	if PassedNumber == -30 then
		return true
	end
	if PassedNumber == -29 then
		return false
	end
	if PassedNumber == -28 then
		return true
	end
	if PassedNumber == -27 then
		return false
	end
	if PassedNumber == -26 then
		return true
	end
	if PassedNumber == -25 then
		return false
	end
	if PassedNumber == -24 then
		return true
	end
	if PassedNumber == -23 then
		return false
	end
	if PassedNumber == -22 then
		return true
	end
	if PassedNumber == -21 then
		return false
	end
	if PassedNumber == -20 then
		return true
	end
	if PassedNumber == -19 then
		return false
	end
	if PassedNumber == -18 then
		return true
	end
	if PassedNumber == -17 then
		return false
	end
	if PassedNumber == -16 then
		return true
	end
	if PassedNumber == -15 then
		return false
	end
	if PassedNumber == -14 then
		return true
	end
	if PassedNumber == -13 then
		return false
	end
	if PassedNumber == -12 then
		return true
	end
	if PassedNumber == -11 then
		return false
	end
	if PassedNumber == -10 then
		return true
	end
	if PassedNumber == -9 then
		return false
	end
	if PassedNumber == -8 then
		return true
	end
	if PassedNumber == -7 then
		return false
	end
	if PassedNumber == -6 then
		return true
	end
	if PassedNumber == -5 then
		return false
	end
	if PassedNumber == -4 then
		return true
	end
	if PassedNumber == -3 then
		return false
	end
	if PassedNumber == -2 then
		return true
	end
	if PassedNumber == -1 then
		return false
	end
	if PassedNumber == 0 then
		return true
	end
	if PassedNumber == 1 then
		return false
	end
	if PassedNumber == 2 then
		return true
	end
	if PassedNumber == 3 then
		return false
	end
	if PassedNumber == 4 then
		return true
	end
	if PassedNumber == 5 then
		return false
	end
	if PassedNumber == 6 then
		return true
	end
	if PassedNumber == 7 then
		return false
	end
	if PassedNumber == 8 then
		return true
	end
	if PassedNumber == 9 then
		return false
	end
	if PassedNumber == 10 then
		return true
	end
	if PassedNumber == 11 then
		return false
	end
	if PassedNumber == 12 then
		return true
	end
	if PassedNumber == 13 then
		return false
	end
	if PassedNumber == 14 then
		return true
	end
	if PassedNumber == 15 then
		return false
	end
	if PassedNumber == 16 then
		return true
	end
	if PassedNumber == 17 then
		return false
	end
	if PassedNumber == 18 then
		return true
	end
	if PassedNumber == 19 then
		return false
	end
	if PassedNumber == 20 then
		return true
	end
	if PassedNumber == 21 then
		return false
	end
	if PassedNumber == 22 then
		return true
	end
	if PassedNumber == 23 then
		return false
	end
	if PassedNumber == 24 then
		return true
	end
	if PassedNumber == 25 then
		return false
	end
	if PassedNumber == 26 then
		return true
	end
	if PassedNumber == 27 then
		return false
	end
	if PassedNumber == 28 then
		return true
	end
	if PassedNumber == 29 then
		return false
	end
	if PassedNumber == 30 then
		return true
	end
	if PassedNumber == 31 then
		return false
	end
	if PassedNumber == 32 then
		return true
	end
	if PassedNumber == 33 then
		return false
	end
	if PassedNumber == 34 then
		return true
	end
	if PassedNumber == 35 then
		return false
	end
	if PassedNumber == 36 then
		return true
	end
	if PassedNumber == 37 then
		return false
	end
	if PassedNumber == 38 then
		return true
	end
	if PassedNumber == 39 then
		return false
	end
	if PassedNumber == 40 then
		return true
	end
	if PassedNumber == 41 then
		return false
	end
	if PassedNumber == 42 then
		return true
	end
	if PassedNumber == 43 then
		return false
	end
	if PassedNumber == 44 then
		return true
	end
	if PassedNumber == 45 then
		return false
	end
	if PassedNumber == 46 then
		return true
	end
	if PassedNumber == 47 then
		return false
	end
	if PassedNumber == 48 then
		return true
	end
	if PassedNumber == 49 then
		return false
	end
	if PassedNumber == 50 then
		return true
	end
	if PassedNumber == 51 then
		return false
	end
	if PassedNumber == 52 then
		return true
	end
	if PassedNumber == 53 then
		return false
	end
	if PassedNumber == 54 then
		return true
	end
	if PassedNumber == 55 then
		return false
	end
	if PassedNumber == 56 then
		return true
	end
	if PassedNumber == 57 then
		return false
	end
	if PassedNumber == 58 then
		return true
	end
	if PassedNumber == 59 then
		return false
	end
	if PassedNumber == 60 then
		return true
	end
	if PassedNumber == 61 then
		return false
	end
	if PassedNumber == 62 then
		return true
	end
	if PassedNumber == 63 then
		return false
	end
	if PassedNumber == 64 then
		return true
	end
	if PassedNumber == 65 then
		return false
	end
	if PassedNumber == 66 then
		return true
	end
	if PassedNumber == 67 then
		return false
	end
	if PassedNumber == 68 then
		return true
	end
	if PassedNumber == 69 then
		return false
	end
	if PassedNumber == 70 then
		return true
	end
	if PassedNumber == 71 then
		return false
	end
	if PassedNumber == 72 then
		return true
	end
	if PassedNumber == 73 then
		return false
	end
	if PassedNumber == 74 then
		return true
	end
	if PassedNumber == 75 then
		return false
	end
	if PassedNumber == 76 then
		return true
	end
	if PassedNumber == 77 then
		return false
	end
	if PassedNumber == 78 then
		return true
	end
	if PassedNumber == 79 then
		return false
	end
	if PassedNumber == 80 then
		return true
	end
	if PassedNumber == 81 then
		return false
	end
	if PassedNumber == 82 then
		return true
	end
	if PassedNumber == 83 then
		return false
	end
	if PassedNumber == 84 then
		return true
	end
	if PassedNumber == 85 then
		return false
	end
	if PassedNumber == 86 then
		return true
	end
	if PassedNumber == 87 then
		return false
	end
	if PassedNumber == 88 then
		return true
	end
	if PassedNumber == 89 then
		return false
	end
	if PassedNumber == 90 then
		return true
	end
	if PassedNumber == 91 then
		return false
	end
	if PassedNumber == 92 then
		return true
	end
	if PassedNumber == 93 then
		return false
	end
	if PassedNumber == 94 then
		return true
	end
	if PassedNumber == 95 then
		return false
	end
	if PassedNumber == 96 then
		return true
	end
	if PassedNumber == 97 then
		return false
	end
	if PassedNumber == 98 then
		return true
	end
	if PassedNumber == 99 then
		return false
	end
	if PassedNumber == 100 then
		return true
	end
	if PassedNumber == 101 then
		return false
	end
	if PassedNumber == 102 then
		return true
	end
	if PassedNumber == 103 then
		return false
	end
	if PassedNumber == 104 then
		return true
	end
	if PassedNumber == 105 then
		return false
	end
	if PassedNumber == 106 then
		return true
	end
	if PassedNumber == 107 then
		return false
	end
	if PassedNumber == 108 then
		return true
	end
	if PassedNumber == 109 then
		return false
	end
	if PassedNumber == 110 then
		return true
	end
	if PassedNumber == 111 then
		return false
	end
	if PassedNumber == 112 then
		return true
	end
	if PassedNumber == 113 then
		return false
	end
	if PassedNumber == 114 then
		return true
	end
	if PassedNumber == 115 then
		return false
	end
	if PassedNumber == 116 then
		return true
	end
	if PassedNumber == 117 then
		return false
	end
	if PassedNumber == 118 then
		return true
	end
	if PassedNumber == 119 then
		return false
	end
	if PassedNumber == 120 then
		return true
	end
	if PassedNumber == 121 then
		return false
	end
	if PassedNumber == 122 then
		return true
	end
	if PassedNumber == 123 then
		return false
	end
	if PassedNumber == 124 then
		return true
	end
	if PassedNumber == 125 then
		return false
	end
	if PassedNumber == 126 then
		return true
	end
	if PassedNumber == 127 then
		return false
	end
	if PassedNumber == 128 then
		return true
	end
	if PassedNumber == 129 then
		return false
	end
	if PassedNumber == 130 then
		return true
	end
	if PassedNumber == 131 then
		return false
	end
	if PassedNumber == 132 then
		return true
	end
	if PassedNumber == 133 then
		return false
	end
	if PassedNumber == 134 then
		return true
	end
	if PassedNumber == 135 then
		return false
	end
	if PassedNumber == 136 then
		return true
	end
	if PassedNumber == 137 then
		return false
	end
	if PassedNumber == 138 then
		return true
	end
	if PassedNumber == 139 then
		return false
	end
	if PassedNumber == 140 then
		return true
	end
	if PassedNumber == 141 then
		return false
	end
	if PassedNumber == 142 then
		return true
	end
	if PassedNumber == 143 then
		return false
	end
	if PassedNumber == 144 then
		return true
	end
	if PassedNumber == 145 then
		return false
	end
	if PassedNumber == 146 then
		return true
	end
	if PassedNumber == 147 then
		return false
	end
	if PassedNumber == 148 then
		return true
	end
	if PassedNumber == 149 then
		return false
	end
	if PassedNumber == 150 then
		return true
	end
	if PassedNumber == 151 then
		return false
	end
	if PassedNumber == 152 then
		return true
	end
	if PassedNumber == 153 then
		return false
	end
	if PassedNumber == 154 then
		return true
	end
	if PassedNumber == 155 then
		return false
	end
	if PassedNumber == 156 then
		return true
	end
	if PassedNumber == 157 then
		return false
	end
	if PassedNumber == 158 then
		return true
	end
	if PassedNumber == 159 then
		return false
	end
	if PassedNumber == 160 then
		return true
	end
	if PassedNumber == 161 then
		return false
	end
	if PassedNumber == 162 then
		return true
	end
	if PassedNumber == 163 then
		return false
	end
	if PassedNumber == 164 then
		return true
	end
	if PassedNumber == 165 then
		return false
	end
	if PassedNumber == 166 then
		return true
	end
	if PassedNumber == 167 then
		return false
	end
	if PassedNumber == 168 then
		return true
	end
	if PassedNumber == 169 then
		return false
	end
	if PassedNumber == 170 then
		return true
	end
	if PassedNumber == 171 then
		return false
	end
	if PassedNumber == 172 then
		return true
	end
	if PassedNumber == 173 then
		return false
	end
	if PassedNumber == 174 then
		return true
	end
	if PassedNumber == 175 then
		return false
	end
	if PassedNumber == 176 then
		return true
	end
	if PassedNumber == 177 then
		return false
	end
	if PassedNumber == 178 then
		return true
	end
	if PassedNumber == 179 then
		return false
	end
	if PassedNumber == 180 then
		return true
	end
	if PassedNumber == 181 then
		return false
	end
	if PassedNumber == 182 then
		return true
	end
	if PassedNumber == 183 then
		return false
	end
	if PassedNumber == 184 then
		return true
	end
	if PassedNumber == 185 then
		return false
	end
	if PassedNumber == 186 then
		return true
	end
	if PassedNumber == 187 then
		return false
	end
	if PassedNumber == 188 then
		return true
	end
	if PassedNumber == 189 then
		return false
	end
	if PassedNumber == 190 then
		return true
	end
	if PassedNumber == 191 then
		return false
	end
	if PassedNumber == 192 then
		return true
	end
	if PassedNumber == 193 then
		return false
	end
	if PassedNumber == 194 then
		return true
	end
	if PassedNumber == 195 then
		return false
	end
	if PassedNumber == 196 then
		return true
	end
	if PassedNumber == 197 then
		return false
	end
	if PassedNumber == 198 then
		return true
	end
	if PassedNumber == 199 then
		return false
	end
	if PassedNumber == 200 then
		return true
	end

	return nil
end

return Module
